service: lambda-overwatch
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10
  environment:
    accountId: ${env:AWS_ACCOUNT_ID}
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
        - "s3:*"
functions:
  config-update:
    handler: config.update
    events:
      - s3: ${env:OVERWATCH_NAME}_photos
