service: lambda-overwatch
custom:
  requestCompleteTopic: site-check-complete
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
functions:
  make-request:
    handler: make-request.makeRequest
    events:
      - schedule:
          rate: rate(5 minutes)
          input:
            url: https://www.tegud.net/
            snsTopic: ${self:custom.requestCompleteTopic}
  handleRequest:
    handler: handler.handleRequest
    events:
      - sns: ${self:custom.requestCompleteTopic}
  sendToSlack:
    handler: handler.sendToSlack
