service: overwatch

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs6.10

functions:
  makeRequest:
    handler: handler.makeRequest
  handleRequest:
    handler: handler.handleRequest
  sendToSlack:
    handler: handler.sendToSlack
